export const mouseLookTuning = {
  pitchDirection: 1,
  pitchSensitivity: 0.014,
  yawDirection: -1,
  yawSensitivity: 0.014,
} as const;

export const chaseCameraTuning = {
  adsDistance: 4.6,
  adsFov: 42,
  adsHeight: 0.18,
  adsLookAheadDistance: 26,
  adsShoulderOffset: 0.42,
  anchorHeight: 0.9,
  distanceBase: 9,
  distanceSpeedMax: 3,
  distanceSpeedScale: 0.16,
  hipFov: 55,
  followSharpness: 10,
  height: 0.95,
  hipShoulderOffset: 1.15,
  lookAheadDistance: 16,
  shoulderOffsetSharpness: 12,
} as const;

export const flightTuning = {
  bankResponse: 14,
  bankPitchSuppression: 0.4,
  boostDrainPerSecond: 30,
  boostMultiplier: 4.35,
  boostReverseDamping: 7.5,
  boostStrafeDamping: 4.5,
  boostStrafeFactor: 0.32,
  boostRechargePerSecond: 18,
  brakeFactor: 0.7,
  linearDamping: 0.925,
  maxBankRadians: Math.PI / 4,
  maxPitchRadians: Math.PI / 3.25,
  reverseThrust: 14,
  strafeThrust: 21,
  thrustForward: 38,
  verticalThrust: 19,
} as const;

export const motionFeedbackTuning = {
  boostFovBonus: 4,
  engineGlowBase: 0.55,
  engineGlowBoost: 0.95,
  engineGlowSpeedScale: 0.03,
  engineLengthBase: 0.75,
  engineLengthBoost: 1.1,
  engineLengthSpeedScale: 0.05,
  sideThrusterGlowBase: 0.2,
  sideThrusterGlowScale: 0.6,
  sideThrusterLength: 0.42,
  sideThrusterRadius: 0.08,
  maxFovBoost: 12,
  reverseThrusterGlowBase: 0.18,
  reverseThrusterGlowScale: 0.45,
  reverseThrusterLength: 0.34,
  reverseThrusterRadius: 0.065,
  speedForMaxFov: 56,
} as const;

export const worldScaleTuning = {
  planetCountMax: 9,
  planetCountMin: 4,
  planetOrbitBaseDistance: 150,
  planetOrbitHeightRange: 24,
  planetOrbitSpacing: 135,
  planetOrbitVariance: 55,
  planetRadiusMax: 58,
  planetRadiusMin: 12,
  sectorSpan: 1400,
} as const;

export const combatTuning = {
  collisionBounceSpeed: 8,
  collisionCooldownSeconds: 0.45,
  collisionDamageShieldMultiplier: 1.4,
  collisionDamageSpeedThreshold: 18,
  collisionDamageStagger: 22,
  collisionDamageStep: 0.45,
  fireCooldownSeconds: 0.1,
  impactColor: '#7ec8ff',
  impactRadius: 0.34,
  impactTtlSeconds: 0.12,
  maxAimDistance: 1400,
  primaryCameraShakeSeconds: 0.09,
  primaryCameraShakeStrength: 0.18,
  projectileDamage: {
    amount: 18,
    shieldMultiplier: 0.9,
    stagger: 16,
  },
  projectileLength: 0.56,
  projectileColor: '#8ed0ff',
  projectileGlowColor: '#6aa8ff',
  projectileRadius: 0.05,
  projectileRecoilImpulse: 0.55,
  projectileSpawnOffset: 1.6,
  projectileSpeed: 320,
  projectileTtlSeconds: 1.8,
  secondaryCameraShakeSeconds: 0.16,
  secondaryCameraShakeStrength: 0.48,
  secondaryChargeMidSeconds: 0.75,
  secondaryChargeMinSeconds: 0.05,
  secondaryChargeFullSeconds: 1.25,
  secondaryCooldownSeconds: 0.48,
  secondaryProjectileColor: '#c6e4ff',
  secondaryProjectileGlowColor: '#93beff',
  secondaryProjectileLengths: {
    full: 6.2,
    mid: 4.8,
    partial: 3.6,
  },
  secondaryProjectileRadius: 0.16,
  secondaryProjectileRecoilImpulse: 2.6,
  secondaryProjectileShieldMultiplier: {
    full: 1.9,
    mid: 1.55,
    partial: 1.2,
  },
  secondaryProjectileSpeed: 260,
  secondaryProjectileStagger: {
    full: 68,
    mid: 42,
    partial: 20,
  },
  secondaryProjectileTtlSeconds: 2.2,
  secondaryProjectileHullMultiplier: {
    full: 7,
    mid: 4.5,
    partial: 2.2,
  },
  secondaryProjectileImpactRadius: {
    full: 1.2,
    mid: 0.9,
    partial: 0.7,
  },
  shipCollisionRadius: 1.1,
} as const;
